//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_rendez_vous.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agenda", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.model")]
    [System.SerializableAttribute()]
    public partial class Agenda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreneauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatePlanifieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeureDebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeureFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAgendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMedecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private gestion_rendez_vous.ServiceReference1.Medecin MedecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private gestion_rendez_vous.ServiceReference1.RendezVous[] rendezVousField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Creneau {
            get {
                return this.CreneauField;
            }
            set {
                if ((this.CreneauField.Equals(value) != true)) {
                    this.CreneauField = value;
                    this.RaisePropertyChanged("Creneau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatePlanifie {
            get {
                return this.DatePlanifieField;
            }
            set {
                if ((this.DatePlanifieField.Equals(value) != true)) {
                    this.DatePlanifieField = value;
                    this.RaisePropertyChanged("DatePlanifie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeureDebut {
            get {
                return this.HeureDebutField;
            }
            set {
                if ((object.ReferenceEquals(this.HeureDebutField, value) != true)) {
                    this.HeureDebutField = value;
                    this.RaisePropertyChanged("HeureDebut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeureFin {
            get {
                return this.HeureFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HeureFinField, value) != true)) {
                    this.HeureFinField = value;
                    this.RaisePropertyChanged("HeureFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAgenda {
            get {
                return this.IdAgendaField;
            }
            set {
                if ((this.IdAgendaField.Equals(value) != true)) {
                    this.IdAgendaField = value;
                    this.RaisePropertyChanged("IdAgenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMedecin {
            get {
                return this.IdMedecinField;
            }
            set {
                if ((this.IdMedecinField.Equals(value) != true)) {
                    this.IdMedecinField = value;
                    this.RaisePropertyChanged("IdMedecin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lieu {
            get {
                return this.LieuField;
            }
            set {
                if ((object.ReferenceEquals(this.LieuField, value) != true)) {
                    this.LieuField = value;
                    this.RaisePropertyChanged("Lieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public gestion_rendez_vous.ServiceReference1.Medecin Medecin {
            get {
                return this.MedecinField;
            }
            set {
                if ((object.ReferenceEquals(this.MedecinField, value) != true)) {
                    this.MedecinField = value;
                    this.RaisePropertyChanged("Medecin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((object.ReferenceEquals(this.StatutField, value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public gestion_rendez_vous.ServiceReference1.RendezVous[] rendezVous {
            get {
                return this.rendezVousField;
            }
            set {
                if ((object.ReferenceEquals(this.rendezVousField, value) != true)) {
                    this.rendezVousField = value;
                    this.RaisePropertyChanged("rendezVous");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medecin", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.model")]
    [System.SerializableAttribute()]
    public partial class Medecin : gestion_rendez_vous.ServiceReference1.Utilisateur {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdspecialiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroOrdreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private gestion_rendez_vous.ServiceReference1.Agenda[] agendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private gestion_rendez_vous.ServiceReference1.specialite specialiteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Idspecialite {
            get {
                return this.IdspecialiteField;
            }
            set {
                if ((this.IdspecialiteField.Equals(value) != true)) {
                    this.IdspecialiteField = value;
                    this.RaisePropertyChanged("Idspecialite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroOrdre {
            get {
                return this.NumeroOrdreField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroOrdreField, value) != true)) {
                    this.NumeroOrdreField = value;
                    this.RaisePropertyChanged("NumeroOrdre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public gestion_rendez_vous.ServiceReference1.Agenda[] agenda {
            get {
                return this.agendaField;
            }
            set {
                if ((object.ReferenceEquals(this.agendaField, value) != true)) {
                    this.agendaField = value;
                    this.RaisePropertyChanged("agenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public gestion_rendez_vous.ServiceReference1.specialite specialite {
            get {
                return this.specialiteField;
            }
            set {
                if ((object.ReferenceEquals(this.specialiteField, value) != true)) {
                    this.specialiteField = value;
                    this.RaisePropertyChanged("specialite");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RendezVous", Namespace="http://schemas.datacontract.org/2004/07/gestion_rendez_vous.model")]
    [System.SerializableAttribute()]
    public partial class RendezVous : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDemandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeureDebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeureFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMedecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMoyenPaiementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private gestion_rendez_vous.ServiceReference1.patient PatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private gestion_rendez_vous.ServiceReference1.Medecin medecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private gestion_rendez_vous.ServiceReference1.MoyenPaiement moyenPaiementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private gestion_rendez_vous.ServiceReference1.Soin soinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDemande {
            get {
                return this.DateDemandeField;
            }
            set {
                if ((this.DateDemandeField.Equals(value) != true)) {
                    this.DateDemandeField = value;
                    this.RaisePropertyChanged("DateDemande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeureDebut {
            get {
                return this.HeureDebutField;
            }
            set {
                if ((object.ReferenceEquals(this.HeureDebutField, value) != true)) {
                    this.HeureDebutField = value;
                    this.RaisePropertyChanged("HeureDebut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeureFin {
            get {
                return this.HeureFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HeureFinField, value) != true)) {
                    this.HeureFinField = value;
                    this.RaisePropertyChanged("HeureFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMedecin {
            get {
                return this.IdMedecinField;
            }
            set {
                if ((this.IdMedecinField.Equals(value) != true)) {
                    this.IdMedecinField = value;
                    this.RaisePropertyChanged("IdMedecin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMoyenPaiement {
            get {
                return this.IdMoyenPaiementField;
            }
            set {
                if ((this.IdMoyenPaiementField.Equals(value) != true)) {
                    this.IdMoyenPaiementField = value;
                    this.RaisePropertyChanged("IdMoyenPaiement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPatient {
            get {
                return this.IdPatientField;
            }
            set {
                if ((this.IdPatientField.Equals(value) != true)) {
                    this.IdPatientField = value;
                    this.RaisePropertyChanged("IdPatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRv {
            get {
                return this.IdRvField;
            }
            set {
                if ((this.IdRvField.Equals(value) != true)) {
                    this.IdRvField = value;
                    this.RaisePropertyChanged("IdRv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSoin {
            get {
                return this.IdSoinField;
            }
            set {
                if ((this.IdSoinField.Equals(value) != true)) {
                    this.IdSoinField = value;
                    this.RaisePropertyChanged("IdSoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public gestion_rendez_vous.ServiceReference1.patient Patient {
            get {
                return this.PatientField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientField, value) != true)) {
                    this.PatientField = value;
                    this.RaisePropertyChanged("Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((object.ReferenceEquals(this.StatutField, value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public gestion_rendez_vous.ServiceReference1.Medecin medecin {
            get {
                return this.medecinField;
            }
            set {
                if ((object.ReferenceEquals(this.medecinField, value) != true)) {
                    this.medecinField = value;
                    this.RaisePropertyChanged("medecin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public gestion_rendez_vous.ServiceReference1.MoyenPaiement moyenPaiement {
            get {
                return this.moyenPaiementField;
            }
            set {
                if ((object.ReferenceEquals(this.moyenPaiementField, value) != true)) {
                    this.moyenPaiementField = value;
                    this.RaisePropertyChanged("moyenPaiement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public gestion_rendez_vous.ServiceReference1.Soin soin {
            get {
                return this.soinField;
            }
            set {
                if ((object.ReferenceEquals(this.soinField, value) != true)) {
                    this.soinField = value;
                    this.RaisePropertyChanged("soin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="personne", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(gestion_rendez_vous.ServiceReference1.patient))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(gestion_rendez_vous.ServiceReference1.Utilisateur))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(gestion_rendez_vous.ServiceReference1.Medecin))]
    public partial class personne : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdU {
            get {
                return this.IdUField;
            }
            set {
                if ((this.IdUField.Equals(value) != true)) {
                    this.IdUField = value;
                    this.RaisePropertyChanged("IdU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPrenom {
            get {
                return this.NomPrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPrenomField, value) != true)) {
                    this.NomPrenomField = value;
                    this.RaisePropertyChanged("NomPrenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="patient", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.model")]
    [System.SerializableAttribute()]
    public partial class patient : gestion_rendez_vous.ServiceReference1.personne {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateNaissanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupeSanguinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> PoidsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> TailleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateNaissance {
            get {
                return this.DateNaissanceField;
            }
            set {
                if ((this.DateNaissanceField.Equals(value) != true)) {
                    this.DateNaissanceField = value;
                    this.RaisePropertyChanged("DateNaissance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupeSanguin {
            get {
                return this.GroupeSanguinField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupeSanguinField, value) != true)) {
                    this.GroupeSanguinField = value;
                    this.RaisePropertyChanged("GroupeSanguin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Poids {
            get {
                return this.PoidsField;
            }
            set {
                if ((this.PoidsField.Equals(value) != true)) {
                    this.PoidsField = value;
                    this.RaisePropertyChanged("Poids");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Taille {
            get {
                return this.TailleField;
            }
            set {
                if ((this.TailleField.Equals(value) != true)) {
                    this.TailleField = value;
                    this.RaisePropertyChanged("Taille");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utilisateur", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(gestion_rendez_vous.ServiceReference1.Medecin))]
    public partial class Utilisateur : gestion_rendez_vous.ServiceReference1.personne {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifiantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotdepasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private gestion_rendez_vous.ServiceReference1.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRole {
            get {
                return this.IdRoleField;
            }
            set {
                if ((this.IdRoleField.Equals(value) != true)) {
                    this.IdRoleField = value;
                    this.RaisePropertyChanged("IdRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifiant {
            get {
                return this.IdentifiantField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifiantField, value) != true)) {
                    this.IdentifiantField = value;
                    this.RaisePropertyChanged("Identifiant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motdepasse {
            get {
                return this.MotdepasseField;
            }
            set {
                if ((object.ReferenceEquals(this.MotdepasseField, value) != true)) {
                    this.MotdepasseField = value;
                    this.RaisePropertyChanged("Motdepasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public gestion_rendez_vous.ServiceReference1.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.model")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string libelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string libelle {
            get {
                return this.libelleField;
            }
            set {
                if ((object.ReferenceEquals(this.libelleField, value) != true)) {
                    this.libelleField = value;
                    this.RaisePropertyChanged("libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="specialite", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.model")]
    [System.SerializableAttribute()]
    public partial class specialite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdspecialiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeSpecialiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomSpecialiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idspecialite {
            get {
                return this.IdspecialiteField;
            }
            set {
                if ((this.IdspecialiteField.Equals(value) != true)) {
                    this.IdspecialiteField = value;
                    this.RaisePropertyChanged("Idspecialite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codeSpecialite {
            get {
                return this.codeSpecialiteField;
            }
            set {
                if ((object.ReferenceEquals(this.codeSpecialiteField, value) != true)) {
                    this.codeSpecialiteField = value;
                    this.RaisePropertyChanged("codeSpecialite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomSpecialite {
            get {
                return this.nomSpecialiteField;
            }
            set {
                if ((object.ReferenceEquals(this.nomSpecialiteField, value) != true)) {
                    this.nomSpecialiteField = value;
                    this.RaisePropertyChanged("nomSpecialite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoyenPaiement", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.model")]
    [System.SerializableAttribute()]
    public partial class MoyenPaiement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMoyenPaiementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string libelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomMPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMoyenPaiement {
            get {
                return this.IdMoyenPaiementField;
            }
            set {
                if ((this.IdMoyenPaiementField.Equals(value) != true)) {
                    this.IdMoyenPaiementField = value;
                    this.RaisePropertyChanged("IdMoyenPaiement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string libelle {
            get {
                return this.libelleField;
            }
            set {
                if ((object.ReferenceEquals(this.libelleField, value) != true)) {
                    this.libelleField = value;
                    this.RaisePropertyChanged("libelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomMP {
            get {
                return this.nomMPField;
            }
            set {
                if ((object.ReferenceEquals(this.nomMPField, value) != true)) {
                    this.nomMPField = value;
                    this.RaisePropertyChanged("nomMP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Soin", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.model")]
    [System.SerializableAttribute()]
    public partial class Soin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomSoinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cout {
            get {
                return this.CoutField;
            }
            set {
                if ((object.ReferenceEquals(this.CoutField, value) != true)) {
                    this.CoutField = value;
                    this.RaisePropertyChanged("Cout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSoin {
            get {
                return this.IdSoinField;
            }
            set {
                if ((this.IdSoinField.Equals(value) != true)) {
                    this.IdSoinField = value;
                    this.RaisePropertyChanged("IdSoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Libelle {
            get {
                return this.LibelleField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleField, value) != true)) {
                    this.LibelleField = value;
                    this.RaisePropertyChanged("Libelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomSoin {
            get {
                return this.nomSoinField;
            }
            set {
                if ((object.ReferenceEquals(this.nomSoinField, value) != true)) {
                    this.nomSoinField = value;
                    this.RaisePropertyChanged("nomSoin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        gestion_rendez_vous.ServiceReference1.CompositeType GetDataUsingDataContract(gestion_rendez_vous.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<gestion_rendez_vous.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(gestion_rendez_vous.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAgenda", ReplyAction="http://tempuri.org/IService1/AddAgendaResponse")]
        bool AddAgenda(gestion_rendez_vous.ServiceReference1.Agenda agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAgenda", ReplyAction="http://tempuri.org/IService1/AddAgendaResponse")]
        System.Threading.Tasks.Task<bool> AddAgendaAsync(gestion_rendez_vous.ServiceReference1.Agenda agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAgenda", ReplyAction="http://tempuri.org/IService1/UpdateAgendaResponse")]
        bool UpdateAgenda(gestion_rendez_vous.ServiceReference1.Agenda agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAgenda", ReplyAction="http://tempuri.org/IService1/UpdateAgendaResponse")]
        System.Threading.Tasks.Task<bool> UpdateAgendaAsync(gestion_rendez_vous.ServiceReference1.Agenda agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListeAgenda", ReplyAction="http://tempuri.org/IService1/GetListeAgendaResponse")]
        gestion_rendez_vous.ServiceReference1.Agenda[] GetListeAgenda();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListeAgenda", ReplyAction="http://tempuri.org/IService1/GetListeAgendaResponse")]
        System.Threading.Tasks.Task<gestion_rendez_vous.ServiceReference1.Agenda[]> GetListeAgendaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMedecinbyId", ReplyAction="http://tempuri.org/IService1/GetMedecinbyIdResponse")]
        gestion_rendez_vous.ServiceReference1.Medecin GetMedecinbyId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMedecinbyId", ReplyAction="http://tempuri.org/IService1/GetMedecinbyIdResponse")]
        System.Threading.Tasks.Task<gestion_rendez_vous.ServiceReference1.Medecin> GetMedecinbyIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : gestion_rendez_vous.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<gestion_rendez_vous.ServiceReference1.IService1>, gestion_rendez_vous.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public gestion_rendez_vous.ServiceReference1.CompositeType GetDataUsingDataContract(gestion_rendez_vous.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<gestion_rendez_vous.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(gestion_rendez_vous.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool AddAgenda(gestion_rendez_vous.ServiceReference1.Agenda agenda) {
            return base.Channel.AddAgenda(agenda);
        }
        
        public System.Threading.Tasks.Task<bool> AddAgendaAsync(gestion_rendez_vous.ServiceReference1.Agenda agenda) {
            return base.Channel.AddAgendaAsync(agenda);
        }
        
        public bool UpdateAgenda(gestion_rendez_vous.ServiceReference1.Agenda agenda) {
            return base.Channel.UpdateAgenda(agenda);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAgendaAsync(gestion_rendez_vous.ServiceReference1.Agenda agenda) {
            return base.Channel.UpdateAgendaAsync(agenda);
        }
        
        public gestion_rendez_vous.ServiceReference1.Agenda[] GetListeAgenda() {
            return base.Channel.GetListeAgenda();
        }
        
        public System.Threading.Tasks.Task<gestion_rendez_vous.ServiceReference1.Agenda[]> GetListeAgendaAsync() {
            return base.Channel.GetListeAgendaAsync();
        }
        
        public gestion_rendez_vous.ServiceReference1.Medecin GetMedecinbyId(int id) {
            return base.Channel.GetMedecinbyId(id);
        }
        
        public System.Threading.Tasks.Task<gestion_rendez_vous.ServiceReference1.Medecin> GetMedecinbyIdAsync(int id) {
            return base.Channel.GetMedecinbyIdAsync(id);
        }
    }
}
